WingineersMeasureItAll/Models/ErrorViewModel.cs
namespace WingineersMeasureItAll.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WingineersMeasureItAll/ViewModels/OrderLineOverviewViewModel.cs
using System;
using System.Globalization;

namespace WingineersMeasureItAll.ViewModels
{
	public class OrderLineOverviewViewModel
	{
		public OrderLineOverviewViewModel()
		{
		}

		public int Month { get; set; }
		public int Year { get; set; }
		public string MonthName {
			get
			{
				return CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(Month);
            }
		}
		public int OrderLineCount { get; set; }
    }
}

WingineersMeasureItAll/ViewModels/SalesPersonDetailsViewModel.cs
using System;
using WingineersMeasureItAll.ApiResponse;

namespace WingineersMeasureItAll.ViewModels
{
	public class SalesPersonDetailsViewModel
	{
        private SalesPerson salesPerson;

        public int Id { get { return salesPerson.Id; } }

        public string? Name { get { return salesPerson.Name; } }

        public DateTime? HireDate { get { return salesPerson.HireDate; } }

        public string? Address { get { return salesPerson.Address; } }

        public string? City { get { return salesPerson.City; } }

        public string? ZipCode { get { return salesPerson.ZipCode; } }

        public List<OrderLine> OrderLines { get; init; }

        public SalesPersonDetailsViewModel(SalesPerson salesPerson, List<OrderLine> orderLines)
        {
            this.salesPerson = salesPerson;
            this.OrderLines = orderLines;
        }


    }
}

WingineersMeasureItAll/ViewModels/SalesPersonOverviewViewModel.cs
using System;
using System.Text.Json.Serialization;
using WingineersMeasureItAll.ApiResponse;

namespace WingineersMeasureItAll.ViewModels
{
    public class SalesPersonOverviewViewModel
    {
        private SalesPerson salesPerson;

        public int Id { get { return salesPerson.Id; } }

        public string? Name { get { return salesPerson.Name; } }

        public DateTime? HireDate { get { return salesPerson.HireDate; } }

        public string? Address { get { return salesPerson.Address; } }

        public string? City { get { return salesPerson.City; } }

        public string? ZipCode { get { return salesPerson.ZipCode; } }

        public int NumberOfOrders { get; } = 0;

        public SalesPersonOverviewViewModel(SalesPerson salesPerson, int numberOfOrders)
		{
            this.salesPerson = salesPerson;
            this.NumberOfOrders = numberOfOrders;
		}
	}
}

WingineersMeasureItAll/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WingineersMeasureItAll.Services;
using WingineersMeasureItAll.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WingineersMeasureItAll.Controllers
{
    public class OrdersController : Controller
    {
        private IWingineersApiProxy wingineersApi;
        public OrdersController(IWingineersApiProxy wingineersApi)
        {
            this.wingineersApi = wingineersApi;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var orderLines = await wingineersApi.GetOrderLines();

            var orderLineCounts = orderLines
                .GroupBy(o => new { o.OrderDate?.Year, o.OrderDate?.Month })
                .Select(x => new OrderLineOverviewViewModel
                {
                    Month = x.Key.Month ?? 0,
                    Year = x.Key.Year ?? 0,
                    OrderLineCount = x.Count()
                })
                .OrderByDescending(x => x.Year)
                .ThenBy(x => x.Month)
                .ToList();

            return View(orderLineCounts);
        }
    }
}

WingineersMeasureItAll/Controllers/SalesPeopleController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc;
using WingineersMeasureItAll.Services;
using WingineersMeasureItAll.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WingineersMeasureItAll.Controllers
{
    public class SalesPeopleController : Controller
    {
        private IWingineersApiProxy wingineersApi;
        public SalesPeopleController(IWingineersApiProxy wingineersApi)
        {
            this.wingineersApi = wingineersApi;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var salesPeople = await wingineersApi.GetSalesPeople();
            var orders = await wingineersApi.GetOrderLines();
            var orderCounts = orders.GroupBy(o => o.SalesPersonId).ToDictionary(group => group.Key, group => group.Count());

            List<SalesPersonOverviewViewModel> viewModel = new List<SalesPersonOverviewViewModel>();

            int currentOrderCount = 0;
            foreach (var salesPerson in salesPeople)
            {
                if (!orderCounts.TryGetValue(salesPerson.Id, out currentOrderCount))
                {
                    currentOrderCount = 0;
                }
                viewModel.Add(new SalesPersonOverviewViewModel(salesPerson, currentOrderCount));
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var salesPeople = await wingineersApi.GetSalesPeople();
            var salesPerson = salesPeople.Find(sp => sp.Id == id);
            var orderLines = await wingineersApi.GetOrderLines();

            var viewModel = new SalesPersonDetailsViewModel(salesPerson, orderLines.FindAll(o => o.SalesPersonId == salesPerson.Id));

            return View(viewModel);
        }
    }
}

WingineersMeasureItAll/Views/Orders/Index.cshtml
@model List<OrderLineOverviewViewModel>

<h2>Order line overview</h2>

<ul>
    @foreach(var orderLineOverviewItem in Model)
    {
       <li>@(orderLineOverviewItem.Year), @(orderLineOverviewItem.MonthName): @(orderLineOverviewItem.OrderLineCount)</li>
    }
</ul>

WingineersMeasureItAll/Views/SalesPeople/Details.cshtml
@model SalesPersonDetailsViewModel

<h2>Details</h2>

<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>@(Model.Name)</td>
        </tr>
        <tr>
            <th>Zip code</th>
            <td>@(Model.ZipCode)</td>
        </tr>
        <tr>
            <th>City</th>
            <td>@(Model.City)</td>
        </tr>
        <tr>
            <th>Address</th>
            <td>@(Model.Address)</td>
        </tr>
        <tr>
            <th>Hire date</th>
            <td>@(Model.HireDate)</td>
        </tr>
    </tbody>
</table>

<h2>Orders</h2>

<table class="table">
    <thead>
        <tr>
            <th>Order number</th>
            <th>Name</th>
            <th>Price</th>
            <th>Placed at</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orderLine in Model.OrderLines)
        {
            <tr>
                <td>@(orderLine.Id)</td>
                <td>@(orderLine.OrderName)</td>
                <td>@(orderLine.OrderPrice)</td>
                <td>@(orderLine.OrderDate)</td>
            </tr>
        }
    </tbody>
</table>

WingineersMeasureItAll/Views/SalesPeople/Index.cshtml
@model List<SalesPersonOverviewViewModel>

<h2>Sales people</h2>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Zip code</th>
            <th>City</th>
            <th>Address</th>
            <th>Hire date</th>
            <th>Number of orders</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var salesPerson in Model)
        {
            <tr>
                <td><a href="@(Url.Action("Details", "SalesPeople", new { id = salesPerson.Id }))">@(salesPerson.Name)</a></td>
                <td>@(salesPerson.ZipCode)</td>
                <td>@(salesPerson.City)</td>
                <td>@(salesPerson.Address)</td>
                <td>@(salesPerson.HireDate)</td>
                <td>@(salesPerson.NumberOfOrders)</td>
            </tr>
        }
    </tbody>
</table>

WingineersMeasureItAll/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WingineersMeasureItAll</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WingineersMeasureItAll.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="SalesPeople" asp-action="Index">WingineersMeasureItAll</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesPeople" asp-action="Index">Sales people</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Order line overview</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WingineersMeasureItAll - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>